---

- name: Main > get proxmox version
  shell: pveversion | cut -d'/' -f2
  register: __proxmox_version
  changed_when: false

# assume 6.0 if cannot determine version (i.e. in check mode)
- set_fact:
    proxmoxy__pve_version: "{{ __proxmox_version.stdout if __proxmox_version.stdout is 
                            defined else '6.0' }}"
    # cacheable: yes

# Host system
- ansible.builtin.include_tasks: host.yml
  tags:
    - proxmoxy

# Permissions
- ansible.builtin.include_tasks: permission.yml
  tags:
    - proxmoxy

# Storage
- ansible.builtin.include_tasks: storage.yml
  tags:
    - proxmoxy

# Templates
- ansible.builtin.include_tasks: templates.yml
  tags:
    - proxmoxy

# Provisioning
- ansible.builtin.include_tasks: prov.yml
  tags:
    - proxmoxy
